### PR TITLE
Add a linkerd config validation by a command line (#1796)

### PR DESCRIPTION
**Pull request by LukaszMarchewka**
Added validation for a configuration.

Solves #1796

### CODE REVIEW

**Comment by LukaszMarchewka** [comment]
I have added validation only for a linkerd. If it is ok then i can implement it for a namer too.

**Comment by LukaszMarchewka** [comment]
@adleong I have changed the commit according your suggestions. Could you verify it ?

**Comment by LukaszMarchewka** [comment]
@adleong I have just move some part of a code from the `main` method to the new `run` method (the code is exactly the same). The `main` method is responsible for parameters "parsing" and then starting a linkerd via the `run` method. In my opinion this code is more readable than adding `if` statement into the `main` method. But if you want I can change it.

**Comment by adleong** [comment]
The main method is already quite short so breaking it up hinders readability in my opinion.  And refactors that don't improve the quality of the code make navigating the git history a bit more difficult.  I think this should just be as simple as adding `if (validate()) return` to the existing main.  There are also some formatting changes in this diff that I think should be reverted.  Thanks again for working on this and for considering my feedback.

**Pull request merged**
