### PR TITLE
Set default TBinaryProtocol.readLength to 10MiB (#1524)

### LINKED ISSUE #1524: namerd fails with OutOfMemoryError on specially crafted request to thrift endpoint
STR:
1. prepare simple config
```
$ cat namerd.yaml
storage:
  kind: io.l5d.inMemory
interfaces:
- kind: io.l5d.thriftNameInterpreter
  port: 4100
```
2. run namerd
```
$ export JVM_OPTIONS="-Xmx1024m"
$ ./namerd-1.1.2-exec namerd.yaml
```
3. send request
```
$ echo -n -e \\x00\\x00\\x00\\x08\\x4e\\x49\\x5f\\x50\\x49\\x4e\\x47\\x00 | nc localhost 4100
```

AR:
namerd fails with OutOfMemoryError and following stacktrace
```
java.lang.OutOfMemoryError: Java heap space
        at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:360)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:221)
        at com.twitter.finagle.thriftmux.ThriftEmulator$Emulator.liftedTree1$1(ThriftEmulator.scala:159)
        at com.twitter.finagle.thriftmux.ThriftEmulator$Emulator.<init>(ThriftEmulator.scala:155)
        at com.twitter.finagle.thriftmux.ThriftEmulator$Init.$anonfun$read$1(ThriftEmulator.scala:125)
        at com.twitter.finagle.thriftmux.ThriftEmulator$Init$$Lambda$777/835600625.apply(Unknown Source)
        at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1129)
        at com.twitter.util.Future$$Lambda$776/149309490.apply(Unknown Source)
        at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:226)
        at com.twitter.util.Promise$Transformer.k(Promise.scala:226)
        at com.twitter.util.Promise$Transformer.apply(Promise.scala:236)
        at com.twitter.util.Promise$Transformer.apply(Promise.scala:217)
        at com.twitter.util.Promise$$anon$7.run(Promise.scala:530)
        at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
        at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
        at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
        at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
        at com.twitter.util.Promise.runq(Promise.scala:520)
        at com.twitter.util.Promise.updateIfEmpty(Promise.scala:883)
        at com.twitter.util.Promise.update(Promise.scala:857)
        at com.twitter.util.Promise.setValue(Promise.scala:833)
        at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
        at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
```

The issue, is that this request appears to be a valid thrift message from finagle point of view, and it says, that there's a string of `4e 49 5f 50` bytes long (which is roughly 1.2 GB)

Let me know, if any additional details are required

### PR DESCRIPTION
**Pull request by edio**
This is an alternative simpler approach to fix #1524 

Probably, can be even combined with the solution proposed by @adleong

### CODE REVIEW

**Comment by edio** [comment]
@adleong Just one thing I wanted to ask. I made this PR at home, where I had no access to metrics.

Now I checked, and I see that the largest request payload ever recorded in our environment is 166 bytes (I'm talking about `interface/io.l5d.thriftNameInterpreter/thrift/request_payload_bytes.max` metric)

Probably 10MiB is way too much. Do you have any info, on how large normal request may be?

**Comment by adleong** [comment]
One thing to keep in mind is that this affects Linkerd's thrift proxying as well (it is susceptible to the same issue).  10MiB is way more than enough for the thrift namer interface but it seems like a reasonable default for thrift messages in general.

**Comment by adleong** [comment]
For reference, the default maximum size for a non-chunked HTTP request is 5120KB (approx 5MB) so this is pretty similar.
https://linkerd.io/config/1.1.2/linkerd/index.html#http-1-1-protocol

**Comment by adleong** [comment]
I've tested this locally.

**Comment by edio** [comment]
@olix0r I've tested it with the request from bug-report - no OOMs.
If you asked about any regressions: we limited read line to 4K on our dev environment.
So far I can only say, that namerds are operational. If we see no issues after couple of days (and tbh I don't expect any), we'll roll-out that further.

**Comment by olix0r** [comment]
I'm not too worried about regressions in this case. if it works, ship it

**Comment by adleong** [comment]
@edio could I get you to sign our CLA so that I can accept this PR?  thanks!!!
https://buoyant.io/cla/

**Comment by edio** [comment]
@adleong done

**Comment by adleong** [comment]
Thanks!

**Pull request merged**
