### PR TITLE
 Disable autoloading of the default tracer (#1477)

### PR DESCRIPTION
**Pull request by mmrozek**
I disabled default tracer - switched to NullTracer in all interfaces.

### CODE REVIEW

**Comment by adleong** [comment]
Looks like it was an issue with the CI system itself.  I've restarted the CI build.  Sorry about that!

**Comment by adleong** [comment]
This looks like a good fix for Namerd, though I think the issue still affects Linkerd.

**Comment by adleong** [comment]
Ah, nevermind, I see that the original issue refers to Namerd.  This looks great to me!

**Comment by dadjeibaah** [comment]
Adding the related issue.

fixes #1477

**Pull request merged**
