### PR TITLE
Change http to https for security links

### PR DESCRIPTION
**Pull request by trungnvfet**

### CODE REVIEW

**Comment by dadjeibaah** [comment]
@trungnvfet, do you mind resolving the merge conflicts? It looks like the conflicts are a result of the other doc PRs that made it onto master.

**Comment by adleong** [comment]
@wmorgan I think this needs your approval because it touches CHANGES.md

**Comment by dadjeibaah** [comment]
@trungnvfet do you mind resolving the merge conflict after that this is ready to merge.

**Comment by adleong** [comment]
Closed due to inactivity.

**Pull request closed without merging**
