### PR TITLE
Update config.md

### PR DESCRIPTION
**Pull request by peterfich**
5 top levels keys since version 0.9.

### CODE REVIEW

**Comment by wmorgan** [comment]
Thanks @peterfich!

**Comment by adleong** [comment]
@peterfich I know this is silly for a docs fix, but our DCO robot will be much happier if you could amend your commit to include the DCO signoff (the `-s` option in git will do this).

**Comment by peterfich** [comment]
Hi Alex,

Can I sign off my own PR?

Will do if I find more to fix. Thanks for accepting it anyway.


Peter

**Comment by adleong** [comment]
Thank you!

**Pull request merged**
