### PR TITLE
Use the default (INFO) tracer log level

### PR DESCRIPTION
**Pull request by thedebugger**
- tracer's TRACE log level doesn't log anything; not sure why

### CODE REVIEW

**Comment by adleong** [comment]
The log level in the tracelog config indicates the level at which traces is logged at.  When set to TRACE, this means that traces are logged at the TRACE level.  If this is below your logging threshold, you won't see them.  The log threshold can be configured with the `-log.level=TRACE` flag or at runtime in the logging tab of the linkerd admin dashboard.

**Comment by thedebugger** [comment]
@adleong ahh, that makes sense. I thought we are setting the logger level to the given level. Actually, we are trying to log the traces with the given level. I'll update the docs to make it more clear. Thanks!

**Comment by adleong** [comment]
Thanks for the doc update!  Can you revert your changes to the example configs?

**Comment by klingerf** [comment]
Fixed by #1514.

**Pull request closed without merging**
