### PR TITLE
Support ServiceInstance objects with a custom payload

### PR DESCRIPTION
**Pull request by dhay**
Reworked the patch to use AnyRef instead of Object when replacing the Void type for ServiceDiscovery and ServiceInstance.

### CODE REVIEW

**Comment by adleong** [comment]
@halve: could you take a look at this and let me know if this works for you?

**Comment by adleong** [comment]
@halve were you able to take a look at this?

**Comment by adleong** [comment]
Closing due to inactivity.  Please reopen if you are still interested in this.

**Comment by dhay** [comment]
Was there something you were waiting for from me on this pull request?  It's still something we would like to see in the core product.

**Comment by adleong** [comment]
Hi @dhay.  Sorry for the inactivity here.  I would really like to get @halve's input on this as I believe they are using it in production and I'm personally a little unclear on the implications of this change.  However, I've been having trouble getting in contact with him.  I will try pinging again.

**Comment by halve** [comment]
Sorry for going MIA. This branch looks great. It wont affect us.

**Pull request merged**
