### PR TITLE
add XFF header into linkerd downstream and access log

### PR DESCRIPTION
**Pull request by leozc**
A prototype adding XFF header to linkerd
1. passing & updating XFF to downstream 
2. add XFF to access log

TODO: How to get the machine IP for linkerd?

```
      class ClientFilter extends SimpleFilter[Request, Response] {
        def apply(req: Request, service: Service[Request, Response]) = {
          val currentHopIP = "0.0.0.0" //FIXME:Where to get my IP?

          if (!req.headers.contains(Key))
            req.headers.set(Key, s"""${currentHopIP}""")
          else
            req.headers.set(Key, s"""${req.headers.get(Key)}, ${currentHopIP}""")

          service(req)
        }
      }
```

Ref: https://en.wikipedia.org/wiki/X-Forwarded-For

### CODE REVIEW

**Comment by olix0r** [comment]
linkerd already sets the [`Forwarded` header](https://github.com/BuoyantIO/linkerd/blob/master/router/http/src/main/scala/io/buoyant/router/http/ForwardedFilter.scala), which [supersedes use of XFF](https://tools.ietf.org/html/rfc7239). We can still consider how to log this, but it was a conscious decision to use the newer standard.

**Comment by olix0r** [comment]
I should note that that this is disabled by default, per RFC7239:

> Due to the sensitive nature of the data passed in this header field (see Sections 8.2 and 8.3), this header field should be turned off by default.

And it appears that this isn't exposed via configuration -- we'll add an option.

**Comment by leozc** [comment]
1. Yes I agree with "Forwarded" header is more appropriate 
2. How does it interact with XFF based header - will linkerD ever log it or update or convert to "Forwarded"
3. Reason for asking is to ensure LinkerD access log has sufficient data in all cases, so that individual service can skip implementing access.log and rely on LinkerD access log.

**Comment by olix0r** [comment]
Forwarded header configuration support: https://github.com/BuoyantIO/linkerd/pull/905

We should probably augment this to rewrite XFF as Forwarded _when it can_.  Note that, as the RFC points out, requests with both X-Forwarded-By and X-Forwarded-For headers cannot be upgraded, but upgrade; but requests with only, for instance, XFF, should be upgradeable.  We should add that as an additional stack filter as a followup to that review.

**Comment by esbie** [comment]
@olix0r are we still interested in moving this PR forward?

**Comment by leozc** [comment]
We don't need this now

**Pull request closed without merging**
