### PR TITLE
Update PLUGINS.md

### PR DESCRIPTION
**Pull request by yarosman**
Added static namer plugin

### CODE REVIEW

**Comment by adleong** [comment]
@yarosman I know this seems silly for just a docs change, but would you mind adding the DCO signoff to your commit so that we can accept it?  thanks!

**Comment by yarosman** [comment]
I am sorry, what is DCO?

**Comment by adleong** [comment]
DCO is just a line in your commit message that allows us to accept the change.  Details here: https://github.com/linkerd/linkerd/pull/2177/checks?check_run_id=32414978

**Comment by yarosman** [comment]
@adleong  I added `Signed-off-by`

**Pull request merged**
