### PR TITLE
Add OpenTracing support #1079

### PR DESCRIPTION
**Pull request by malafeev**
Initial proposal for #1079

Create OpenTracing filter to
- Extract span context from http headers of incoming requests (and later use this span context as parent for created span)
- Create span and inject it into http headers of outgoing request.
- Call Trace.recordBinary("opentracing-span", span). It will be intercepted by OpenTracing linkerd plugin (using TelemeterInitializer)

### CODE REVIEW

**Comment by deebo91** [comment]
@malafeev thank you very much for starting a PR for this feature. We always love it when we get a contribution from the community. Let us not when you are ready for us to review this PR!

**Comment by malafeev** [comment]
@deebo91 please review it.
Maybe you will propose another approach.

**Comment by adleong** [comment]
Hi @malafeev!  Thank you for starting work on this!  We're really excited to get Open Tracing support into Linkerd.  Before we dig too much into the implementation details, could you tell us a little more about how this works?

* What are the steps for testing this?
* I don't see the OpenTracing telemeter in this branch, is that in progress?

**Comment by malafeev** [comment]
@adleong I will publish telemeter plugin.

**Comment by adleong** [comment]
Hi @malafeev, have you had a chance to publish the telemetry plugin?

**Comment by malafeev** [comment]
@adleong I'm currently stuck because linkerd uses libthrift version 0.5
but Jaeger tracer uses libthrift version 0.9.2
Most of OpenTracing tracers come with dependencies on transport libraries (thrift, grpc etc)
and they sometimes conflict with application dependencies (jar hell).

**Comment by adleong** [comment]
Yikes.  Unfortunately, I don't have much advice to offer.  Perhaps some kind of dependency shadowing might help?

**Comment by malafeev** [comment]
yeah, trying to solve issue with shadowing (https://github.com/jaegertracing/jaeger-client-java/issues/332)

**Comment by adleong** [comment]
Hi @malafeev, any luck getting the shadowing to work?

**Comment by malafeev** [comment]
Hi @adleong, no luck.
Problem that only Jaeger tracer supports Tracer Resolver, but there is an (issue)[https://github.com/jaegertracing/jaeger-client-java/issues/332#issuecomment-365903790]
which probably will not be fixed nearest time.
I think we can close this PR for now.

**Pull request closed without merging**
