### PR TITLE
 Use fully specified paths so that the generated code doesn't cause ambiguity

### LINKED ISSUE #2346: Using well known types in protobuf file fails with grpc-gen
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

I tried to import:
```proto
import "google/protobuf/timestamp.proto";
```
and then use it:
```proto
message Message {
    google.protobuf.Timestamp stamp = 1;
}
```
When calling `protocjar.Protoc` with `--include_std_types` I get following kinds of errors:
```
[ERROR] target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:11: error: com.google.protobuf.Option does not take type parameter
[ERROR]     `seconds`: Option[Long] = None,                                                                                                                                                           
[ERROR]                ^                                                                                 
[ERROR] target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:12: error: com.google.protobuf.Option does not take type parameter
[ERROR]     `nanos`: Option[Int] = None                                                                                                                                                               
[ERROR]              ^                                                                                   
[ERROR] target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:19: error: com.google.protobuf.Option does not take type parameter
[ERROR]         var secondsArg: Option[Long] = None                                                      
[ERROR]                         ^                                                                                                                                                                     
[ERROR] target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:20: error: com.google.protobuf.Option does not take type parameter
[ERROR]         var nanosArg: Option[Int] = None                                                                                                                                                      
[ERROR]                       ^                                                                                                                                                                       
[ERROR]  target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:29: error: class com.google.protobuf.Option is not a value        
[ERROR]                   secondsArg = Option(pbis.readInt64())                                                                                                                                       
[ERROR]                                ^                                                                 
[ERROR] target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:36: error: class com.google.protobuf.Option is not a value
[ERROR]                   nanosArg = Option(pbis.readInt32())                                            
[ERROR]                              ^                                                                   
[ERROR] target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:51: error: type mismatch;                                         
[ERROR]  found   : Any                                                                                   
[ERROR]  required: Long                                                                                                                                                                               
[ERROR]             pbos.writeInt64(1, value)                                                                                                                                                         
[ERROR]                                ^                                                                 
[ERROR] target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:57: error: type mismatch;
[ERROR]  found   : Any                                                                                   
[ERROR]  required: Int                                                                                   
[ERROR]             pbos.writeInt32(2, value)                                                                                                                                                         
[ERROR]                                ^                                                                 
[ERROR] target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:66: error: type mismatch;
[ERROR]  found   : Any                                                                                   
[ERROR]  required: Long                                                                                  
[ERROR]             val sz = com.google.protobuf.CodedOutputStream.computeTagSize(1) + com.google.protobuf.CodedOutputStream.computeInt64SizeNoTag(value)
[ERROR]                                                                                                                                            ^
[ERROR] target/generated-sources/scala/com/google/protobuf/TimestampProto.pb.scala:72: error: type mismatch;
[ERROR]  found   : Any
[ERROR]  required: Int
[ERROR]             val sz = com.google.protobuf.CodedOutputStream.computeTagSize(2) + com.google.protobuf.CodedOutputStream.computeInt32SizeNoTag(value)
[ERROR]                                                                                                                                            ^
[ERROR] 10 errors found

```

**What you expected to happen**:

`Timestamp` to be built without errors.

**How to reproduce it (as minimally and precisely as possible)**:
Compile the following `.proto` file:
```
syntax = "proto3";
package p;
message Option {}
```

### PR DESCRIPTION
**Pull request by WaDelma**
Fixes #2346

### CODE REVIEW

**Comment by zaharidichev** [comment]
@WaDelma What kind of error are you getting when you try to use Timestamp with the change you made. Is it still based on type name collisions ?

**Comment by adleong** [comment]
Hi @WaDelma.  I don't believe that import of the google standard types is supported by linkerd/grpc.  To work around this, you can copy the `timestamp.proto` file into your repo.

**Comment by WaDelma** [comment]
@zaharidichev The error I was getting was with the `grpc-eg` project. I couldn't figure out how to use well known types with it.

@adleong After publishing to local maven repo and changing our project to use it, I was able to get it to build. We are using `com.github.os72.protocjar` which has flag `--include_std_types`.

So it seems that this PR fixes our problems with the well known types. It should also fix problems if you had messages named `Seq`, `Map`, `Option`, `Some`, `None` or `Nil`.

**Comment by adleong** [comment]
To contribute to this project, you must agree to the Developer Certificate of
Origin (DCO) for each commit you make. The DCO is a simple statement that you,
as a contributor, have the legal right to make the contribution.

See the [DCO](DCO) file for the full text of what you must agree to.

To signify that you agree to the DCO for a commit, you add a line to the
git commit message:

```
Signed-off-by: Jane Smith <jane.smith@example.com>
```

In most cases, you can add this signoff to your commit automatically with the
`-s` flag to `git commit`. You must use your real name and a reachable email
address (sorry, no pseudonyms or anonymous contributions).

**Comment by WaDelma** [comment]
@adleong The only commit in this PR is already signed. What else do I need to do?

I am not the original author of how we use it but as far as I can gather we call shell script with `exec-maven-plugin` which calls `com.github.os72.protocjar` as an executable with `--plugin` flag where the plugin is an another shell script that calls `io.boyant.grpc.gen.Main`.

**Comment by WaDelma** [comment]
So I am supposed to put pseudonym there then?

**Comment by zaharidichev** [comment]
Did you sign it with `git commit --signoff` ?  What you are supposed to put in there I think depends on how your github client is setup. Look at your `git log` output. Your Author name does not match with your signature: 

Screenshot 2019-10-23 at 14 45 52

**Comment by WaDelma** [comment]
@zaharidichev So it should have pseudonym. I changed it to the result of `git commit --signoff`.

**Comment by WaDelma** [comment]
So is this mergeable now?

**Comment by cpretzer** [comment]
@WaDelma it looks like all the checks have passed and you can merge it.

**Comment by WaDelma** [comment]
@cpretzer I don't think I have write access to the repo.

**Comment by zaharidichev** [comment]
Merging that. Thanks a lot @WaDelma. Very good change :)

**Pull request merged**
